#include "Preferences/PlayerConfiguration.h"

#include "Core/Logger.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QSaveFile>
#include <QSettings>
#include <QStandardPaths>
#include <QTextStream>
#include <QVariantList>
#include <QVariantMap>

#include <algorithm>

namespace {
const QString builtInConfigName = QStringLiteral("Supernova Default");
const QString applicationPrefix = QStringLiteral("#@supernova");

QString generatedInputConf(
    const QList<ConfiguredKeyBinding> &bindings)
{
    QString result = QStringLiteral(
        "# Generated by Supernova. Duplicate keys use the last mapping.\n\n");
    for (const ConfiguredKeyBinding &binding : bindings) {
        const QString key = binding.key.trimmed();
        const QString action = binding.action.trimmed();
        if (key.isEmpty() || action.isEmpty()) {
            continue;
        }
        if (binding.applicationCommand) {
            result += applicationPrefix + QLatin1Char(' ');
        }
        result += key + QLatin1Char(' ') + action;
        if (!binding.comment.trimmed().isEmpty()) {
            result += QStringLiteral("   #") + binding.comment.trimmed();
        }
        result += QLatin1Char('\n');
    }
    return result;
}

bool writeAtomically(const QString &path, const QByteArray &contents)
{
    QDir().mkpath(QFileInfo(path).absolutePath());
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }
    if (file.write(contents) != contents.size()) {
        file.cancelWriting();
        return false;
    }
    return file.commit();
}
}

QString PlayerConfiguration::inputConfigDirectory()
{
    return QDir(QStandardPaths::writableLocation(
                    QStandardPaths::AppConfigLocation))
        .filePath(QStringLiteral("input"));
}

QString PlayerConfiguration::mpvConfigDirectory()
{
    const QSettings settings;
    if (settings.value(
            QStringLiteral("advanced/useConfigDirectory"), false).toBool()) {
        const QString configured = settings.value(
            QStringLiteral("advanced/configDirectory")).toString().trimmed();
        if (!configured.isEmpty()) {
            return QDir::cleanPath(QDir::fromNativeSeparators(configured));
        }
    }
    return QDir(QStandardPaths::writableLocation(
                    QStandardPaths::AppConfigLocation))
        .filePath(QStringLiteral("mpv"));
}

QString PlayerConfiguration::mpvConfigFilePath()
{
    return QDir(mpvConfigDirectory()).filePath(QStringLiteral("mpv.conf"));
}

QString PlayerConfiguration::currentInputConfigName()
{
    const QString configured = QSettings().value(
        QStringLiteral("input/currentConfig"),
        builtInConfigName).toString();
    return inputConfigNames().contains(configured)
        ? configured : builtInConfigName;
}

void PlayerConfiguration::setCurrentInputConfigName(const QString &name)
{
    QSettings().setValue(
        QStringLiteral("input/currentConfig"),
        inputConfigNames().contains(name) ? name : builtInConfigName);
}

QStringList PlayerConfiguration::inputConfigNames()
{
    ensureConfigurationFiles();
    QStringList names{builtInConfigName};
    const QFileInfoList files = QDir(inputConfigDirectory()).entryInfoList(
        {QStringLiteral("*.conf")}, QDir::Files, QDir::Name);
    for (const QFileInfo &file : files) {
        const QString name = file.completeBaseName();
        if (name != builtInConfigName) {
            names.append(name);
        }
    }
    return names;
}

bool PlayerConfiguration::isBuiltInInputConfig(const QString &name)
{
    return name == builtInConfigName;
}

QString PlayerConfiguration::inputConfigPath(const QString &name)
{
    ensureConfigurationFiles();
    const QString selected =
        inputConfigNames().contains(name) ? name : builtInConfigName;
    return QDir(inputConfigDirectory()).filePath(selected + QStringLiteral(".conf"));
}

QList<ConfiguredKeyBinding> PlayerConfiguration::defaultKeyBindings()
{
    using Binding = ConfiguredKeyBinding;
    return {
        Binding{QStringLiteral("SPACE"), QStringLiteral("TogglePause"), {}, true},
        Binding{QStringLiteral("LEFT"), QStringLiteral("SeekBackward"), {}, true},
        Binding{QStringLiteral("RIGHT"), QStringLiteral("SeekForward"), {}, true},
        Binding{QStringLiteral("UP"), QStringLiteral("VolumeUp"), {}, true},
        Binding{QStringLiteral("DOWN"), QStringLiteral("VolumeDown"), {}, true},
        Binding{QStringLiteral("PGUP"), QStringLiteral("PreviousMedia"), {}, true},
        Binding{QStringLiteral("PGDWN"), QStringLiteral("NextMedia"), {}, true},
        Binding{QStringLiteral("Ctrl+PGUP"), QStringLiteral("PreviousChapter"), {}, true},
        Binding{QStringLiteral("Ctrl+PGDWN"), QStringLiteral("NextChapter"), {}, true},
        Binding{QStringLiteral("HOME"), QStringLiteral("JumpToBeginning"), {}, true},
        Binding{QStringLiteral(","), QStringLiteral("FrameBackward"), {}, true},
        Binding{QStringLiteral("."), QStringLiteral("FrameForward"), {}, true},
        Binding{QStringLiteral("["), QStringLiteral("SpeedDown"), {}, true},
        Binding{QStringLiteral("]"), QStringLiteral("SpeedUp"), {}, true},
        Binding{QStringLiteral("BS"), QStringLiteral("ResetSpeed"), {}, true},
        Binding{QStringLiteral("m"), QStringLiteral("ToggleMute"), {}, true},
        Binding{QStringLiteral("s"), QStringLiteral("TakeScreenshot"), {}, true},
        Binding{QStringLiteral("l"), QStringLiteral("ToggleAbLoop"), {}, true},
        Binding{QStringLiteral("f"), QStringLiteral("ToggleFullScreen"), {}, true},
        Binding{QStringLiteral("F11"), QStringLiteral("ToggleFullScreen"), {}, true},
        Binding{QStringLiteral("Alt+ENTER"), QStringLiteral("ToggleFullScreen"), {}, true},
        Binding{QStringLiteral("Ctrl+o"), QStringLiteral("OpenFile"), {}, true},
        Binding{QStringLiteral("Ctrl+Shift+o"), QStringLiteral("OpenFolder"), {}, true},
        Binding{QStringLiteral("Ctrl+Shift+i"), QStringLiteral("ImportPlaylist"), {}, true},
        Binding{QStringLiteral("Ctrl+Shift+s"), QStringLiteral("SavePlaylist"), {}, true},
        Binding{QStringLiteral("Ctrl+."), QStringLiteral("Stop"), {}, true},
        Binding{QStringLiteral("Ctrl+Shift+p"), QStringLiteral("TogglePlaylist"), {}, true},
        Binding{QStringLiteral("Ctrl+t"), QStringLiteral("ToggleAlwaysOnTop"), {}, true},
        Binding{QStringLiteral("Ctrl+h"), QStringLiteral("ShowPlaybackHistory"), {}, true},
        Binding{QStringLiteral("Ctrl+i"), QStringLiteral("ShowMediaInspector"), {}, true},
        Binding{QStringLiteral("Ctrl+,"), QStringLiteral("ShowPreferences"), {}, true},
        Binding{QStringLiteral("Ctrl+w"), QStringLiteral("CloseWindow"), {}, true},
        Binding{QStringLiteral("Ctrl+q"), QStringLiteral("QuitApplication"), {}, true},
        Binding{QStringLiteral("ESC"), QStringLiteral("PauseAndMinimize"), {}, true},
    };
}

QList<ConfiguredKeyBinding> PlayerConfiguration::parseInputConf(
    const QString &path, bool *ok)
{
    if (ok) {
        *ok = false;
    }
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return {};
    }

    QList<ConfiguredKeyBinding> bindings;
    QTextStream stream(&file);
    while (!stream.atEnd()) {
        QString line = stream.readLine();
        bool applicationCommand = false;
        const QString trimmed = line.trimmed();
        if (trimmed.isEmpty()) {
            continue;
        }
        if (trimmed.startsWith(applicationPrefix)) {
            applicationCommand = true;
            line = trimmed.mid(applicationPrefix.size()).trimmed();
        } else if (trimmed.startsWith(QLatin1Char('#'))) {
            continue;
        }

        QString comment;
        const qsizetype commentIndex = line.indexOf(QLatin1Char('#'));
        if (commentIndex >= 0) {
            comment = line.mid(commentIndex + 1).trimmed();
            line = line.left(commentIndex);
        }
        const QRegularExpression separator(QStringLiteral("\\s+"));
        const QRegularExpressionMatch match = separator.match(line.trimmed());
        if (!match.hasMatch()) {
            continue;
        }
        const QString key = line.left(match.capturedStart()).trimmed();
        const QString action = line.mid(match.capturedEnd()).trimmed();
        if (!key.isEmpty() && !action.isEmpty()) {
            bindings.append({key, action, comment, applicationCommand});
        }
    }
    if (ok) {
        *ok = true;
    }
    return bindings;
}

QList<ConfiguredKeyBinding> PlayerConfiguration::currentKeyBindings()
{
    bool parsed = false;
    const QList<ConfiguredKeyBinding> bindings = parseInputConf(
        inputConfigPath(currentInputConfigName()), &parsed);
    return parsed ? bindings : defaultKeyBindings();
}

bool PlayerConfiguration::saveInputConfig(
    const QString &name,
    const QList<ConfiguredKeyBinding> &bindings)
{
    if (isBuiltInInputConfig(name)) {
        return false;
    }
    return writeAtomically(
        inputConfigPath(name), generatedInputConf(bindings).toUtf8());
}

bool PlayerConfiguration::createInputConfig(
    const QString &name,
    const QList<ConfiguredKeyBinding> &bindings)
{
    const QString cleanName = sanitizedConfigName(name);
    if (cleanName.isEmpty() || inputConfigNames().contains(cleanName)) {
        return false;
    }
    return writeAtomically(
        QDir(inputConfigDirectory()).filePath(
            cleanName + QStringLiteral(".conf")),
        generatedInputConf(bindings).toUtf8());
}

bool PlayerConfiguration::deleteInputConfig(const QString &name)
{
    if (isBuiltInInputConfig(name)) {
        return false;
    }
    const bool removed = QFile::remove(inputConfigPath(name));
    if (removed && currentInputConfigName() == name) {
        setCurrentInputConfigName(builtInConfigName);
    }
    return removed;
}

bool PlayerConfiguration::importInputConfig(
    const QString &sourcePath, QString *importedName)
{
    const QFileInfo source(sourcePath);
    if (!source.isFile() || source.suffix().compare(
            QStringLiteral("conf"), Qt::CaseInsensitive) != 0) {
        return false;
    }
    const QString name = sanitizedConfigName(source.completeBaseName());
    if (name.isEmpty() || inputConfigNames().contains(name)) {
        return false;
    }
    const QString destination = QDir(inputConfigDirectory()).filePath(
        name + QStringLiteral(".conf"));
    if (!QFile::copy(source.absoluteFilePath(), destination)) {
        return false;
    }
    bool valid = false;
    const QList<ConfiguredKeyBinding> imported =
        parseInputConf(destination, &valid);
    Q_UNUSED(imported)
    if (!valid) {
        QFile::remove(destination);
        return false;
    }
    if (importedName) {
        *importedName = name;
    }
    return true;
}

QList<ConfiguredMpvOption> PlayerConfiguration::advancedOptions()
{
    QList<ConfiguredMpvOption> result;
    const QVariantList stored = QSettings().value(
        QStringLiteral("advanced/options")).toList();
    for (const QVariant &value : stored) {
        const QVariantMap map = value.toMap();
        const QString name = map.value(QStringLiteral("name")).toString().trimmed();
        if (!name.isEmpty()) {
            result.append({
                name,
                map.value(QStringLiteral("value")).toString()});
        }
    }
    return result;
}

void PlayerConfiguration::setAdvancedOptions(
    const QList<ConfiguredMpvOption> &options)
{
    QVariantList stored;
    for (const ConfiguredMpvOption &option : options) {
        if (!option.name.trimmed().isEmpty()) {
            stored.append(QVariantMap{
                {QStringLiteral("name"), option.name.trimmed()},
                {QStringLiteral("value"), option.value}});
        }
    }
    QSettings().setValue(QStringLiteral("advanced/options"), stored);
}

bool PlayerConfiguration::advancedSettingsEnabled()
{
    return QSettings().value(
        QStringLiteral("advanced/enabled"), false).toBool();
}

bool PlayerConfiguration::useCustomConfigDirectory()
{
    return QSettings().value(
        QStringLiteral("advanced/useConfigDirectory"), false).toBool();
}

QString PlayerConfiguration::customConfigDirectory()
{
    return QSettings().value(
        QStringLiteral("advanced/configDirectory"),
        mpvConfigDirectory()).toString();
}

QStringList PlayerConfiguration::mpvProfiles(
    const QString &configurationText)
{
    QStringList profiles;
    const QRegularExpression section(
        QStringLiteral("^\\s*\\[([^\\]]+)\\]\\s*(?:#.*)?$"));
    const QStringList lines = configurationText.split(QLatin1Char('\n'));
    for (const QString &line : lines) {
        const QRegularExpressionMatch match = section.match(line);
        if (!match.hasMatch()) {
            continue;
        }
        const QString name = match.captured(1).trimmed();
        if (!name.isEmpty()
            && name.compare(QStringLiteral("default"), Qt::CaseInsensitive) != 0
            && !profiles.contains(name)) {
            profiles.append(name);
        }
    }
    return profiles;
}

QStringList PlayerConfiguration::mpvProfilesFromDisk()
{
    return mpvProfiles(readMpvConfig());
}

QString PlayerConfiguration::readMpvConfig()
{
    ensureConfigurationFiles();
    QFile file(mpvConfigFilePath());
    return file.open(QIODevice::ReadOnly | QIODevice::Text)
        ? QString::fromUtf8(file.readAll()) : QString();
}

bool PlayerConfiguration::writeMpvConfig(const QString &text)
{
    return writeAtomically(mpvConfigFilePath(), text.toUtf8());
}

void PlayerConfiguration::ensureConfigurationFiles()
{
    QDir().mkpath(inputConfigDirectory());
    QDir().mkpath(mpvConfigDirectory());
    const QString defaultPath = QDir(inputConfigDirectory()).filePath(
        builtInConfigName + QStringLiteral(".conf"));
    // The built-in profile is read-only in the UI and is regenerated so
    // newly introduced application commands reach existing installations.
    writeAtomically(
        defaultPath,
        generatedInputConf(defaultKeyBindings()).toUtf8());
    const QString mpvPath = mpvConfigFilePath();
    if (!QFileInfo::exists(mpvPath)) {
        writeAtomically(
            mpvPath,
            QByteArray("# Supernova mpv configuration\n"
                       "# Add [profile-name] sections to create profiles.\n"));
    }
}

QString PlayerConfiguration::sanitizedConfigName(const QString &name)
{
    QString result = name.trimmed();
    result.remove(QRegularExpression(QStringLiteral("[\\\\/:*?\"<>|]")));
    return result;
}
